use serde::Deserialize;

#[derive(Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Order {
    pub inst_type: String,
    pub inst_id: String,
    pub ccy: String,
    pub ord_id: String,
    pub cl_ord_id: String,
    pub tag: String,
    pub px: String,
    pub sz: String,
    pub ord_type: String,
    pub side: String,
    pub pos_side: String,
    pub td_mode: String,
    pub fill_sz: String,
    pub fill_px: String,
    pub trade_id: String,
    pub acc_fill_sz: String,
    pub fill_time: String,
    pub fill_fee: String,
    pub fill_fee_ccy: String,
    pub exec_type: String,
    pub state: String,
    pub avg_px: String,
    pub lever: String,
    pub tp_trigger_px: String,
    pub tp_ord_px: String,
    pub sl_trigger_px: String,
    pub sl_ord_px: String,
    pub fee_ccy: String,
    pub fee: String,
    pub rebate_ccy: String,
    pub rebate: String,
    pub pnl: String,
    pub category: String,
    pub u_time: String,
    pub c_time: String,
    pub req_id: String,
    pub amend_result: String,
    pub code: String,
    pub msg: String,
}
